name: test1

on: [pull_request]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: npm ci

      - uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: ae-test-company
          repo: ae-automate
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: dispatch.yml
          ref: master